services:
  db:
    image: postgres:16
    container_name: warranty_services_bot_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: ${IMAGE_ROOT}
    env_file: .env
    depends_on:
      - db

volumes:
  postgres_data: