"""Initial revision

Revision ID: 3c8aef31d630
Revises: ed91e1d50722
Create Date: 2025-06-03 21:42:08.630680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8aef31d630'
down_revision: Union[str, None] = 'ed91e1d50722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenancedatas',
    sa.Column('vin', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('dealer_code', sa.String(), nullable=False),
    sa.Column('maintenance_date', sa.String(), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenancedatas')
    # ### end Alembic commands ###
