"""Initial revision

Revision ID: 4351f3025317
Revises: 90cc0276ac3b
Create Date: 2025-06-06 13:57:47.880934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4351f3025317'
down_revision: Union[str, None] = '90cc0276ac3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partsdatas',
    sa.Column('part_number', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('descriprion_en', sa.Text(), nullable=True),
    sa.Column('descriprion_ru', sa.Text(), nullable=True),
    sa.Column('dnp', sa.Float(), nullable=False),
    sa.Column('list_price', sa.Float(), nullable=False),
    sa.Column('mobis_count', sa.Integer(), nullable=False),
    sa.Column('ellias_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partsdatas')
    # ### end Alembic commands ###
