"""Initial revision

Revision ID: 5db20f688843
Revises: 89f7b39a47c9
Create Date: 2025-05-29 16:00:47.169357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5db20f688843'
down_revision: Union[str, None] = '89f7b39a47c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partsdatas',
    sa.Column('part_number', sa.Text(), nullable=False),
    sa.Column('descriprion', sa.String(), nullable=False),
    sa.Column('ellias_count', sa.Integer(), nullable=False),
    sa.Column('mobis_count', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partsdatas')
    # ### end Alembic commands ###
