"""Initial revision

Revision ID: 89f7b39a47c9
Revises: 459da35a3772
Create Date: 2025-05-25 22:08:13.484697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f7b39a47c9'
down_revision: Union[str, None] = '459da35a3772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicledatas', sa.Column('dist_code', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicledatas', 'dist_code')
    # ### end Alembic commands ###
