"""Initial revision

Revision ID: 9ca012074bbd
Revises: 6852450dbd5e
Create Date: 2025-06-09 22:17:34.701826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ca012074bbd'
down_revision: Union[str, None] = '6852450dbd5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicledatas',
    sa.Column('local_vin', sa.Text(), nullable=False),
    sa.Column('dkd_vin', sa.Text(), nullable=False),
    sa.Column('dist_code', sa.String(), nullable=False),
    sa.Column('warranty_start_date', sa.String(), nullable=False),
    sa.Column('engine_number', sa.String(), nullable=False),
    sa.Column('transmission_number', sa.String(), nullable=False),
    sa.Column('key_number', sa.String(), nullable=False),
    sa.Column('body_color', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dkd_vin'),
    sa.UniqueConstraint('local_vin')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicledatas')
    # ### end Alembic commands ###
