"""Initial revision

Revision ID: fc8b84e65311
Revises: de48ea15f856
Create Date: 2025-06-06 13:25:19.562998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc8b84e65311'
down_revision: Union[str, None] = 'de48ea15f856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partsdatas', 'model',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('partsdatas', 'descriprion_en',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('partsdatas', 'descriprion_ru',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partsdatas', 'descriprion_ru',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('partsdatas', 'descriprion_en',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('partsdatas', 'model',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
